# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clean_mrk <- function(data, na_freq = NULL, rm_mono = FALSE, maf = NULL, recode = FALSE, rm_dupes = FALSE, keep = NULL, impute = FALSE, homo = as.character( c("A", "C", "G", "T")), hetero = as.character( c("R", "Y", "S", "W", "K", "M")), homo_num_min = -1L, homo_num_maj = 1L, hetero_num = 0L, row_names = FALSE, verbose = TRUE) {
    .Call(`_clemag_clean_mrk`, data, na_freq, rm_mono, maf, recode, rm_dupes, keep, impute, homo, hetero, homo_num_min, homo_num_maj, hetero_num, row_names, verbose)
}

